language: python
python:
- '3.4'
branches:
  except:
  - master
  - ci
env:
  matrix:
    - FORMAT=hst TF=M1
    - FORMAT=hst TF=M2
    - FORMAT=hst TF=M3
    - FORMAT=hst TF=M4
    - FORMAT=hst TF=M5
    - FORMAT=hst TF=M6
    - FORMAT=hst TF=M10
    - FORMAT=hst TF=M12
    - FORMAT=hst TF=M15
    - FORMAT=hst TF=M20
    - FORMAT=hst TF=M30
    - FORMAT=hst TF=H1
    - FORMAT=hst TF=H2
    - FORMAT=hst TF=H3
    - FORMAT=hst TF=H4
    - FORMAT=hst TF=H6
    - FORMAT=hst TF=H8
    - FORMAT=hst TF=H12
    - FORMAT=hst TF=D1
    - FORMAT=hst TF=W1
    - FORMAT=hst TF=MN1
    - FORMAT=fxt TF=M1
    - FORMAT=fxt TF=M5
    - FORMAT=fxt TF=M15
    - FORMAT=fxt TF=M30
    - FORMAT=fxt TF=H1
    - FORMAT=fxt TF=H4
    - FORMAT=fxt TF=D1
    - FORMAT=fxt TF=W1
    - FORMAT=fxt TF=MN1
addons:
  apt:
    packages:
    - realpath
    - pv
notifications:
  email: false
before_install:
- set -e
install: 
before_script:
- curl -o Makefile https://raw.githubusercontent.com/FX-Data/FX-Data-Test/master/Makefile
script:
- make $FORMAT
after_success: 
after_failure:
- sudo apt-get -qy install tree && tree -d -L 6
- env
after_script:
- pwd
deploy:
  provider: releases
  api_key:
    secure: "GhVMDRvBXpHf9rUjhOEGB1HELq9Gys8YPag2SAbrt6UsaDBF4jvlIowiBDSC3JPEyIZL7t9wLCxxg2X1nLg5rxAbC7TmTJDnSI4ePTCXeK2asrbF2L8tMyUjJKbHz1p2XEXCClYeb0RA4AoZDuV+g/fvrN/2tlGY66DBk82BZAxNltH1QK61vHPgXyKGqAS8GhtSL5u/FDe1qMPGKZFzPBGCs2iZaLmb47jY1RhdSnevzqi1TQbipi78c7jDdjterdyeVsGIQPdh1wAYE6ibIslRYSU7mvXHyothWVdNFygPvall8EP4l+E937kHe54B7Ls86CYzGQEbCvbQw05p2bjgG2DNohhkwFnVB56UuuHqnYPVkrkBdaaAAUxo+iWzo8JBadxfEmAdATPrFqI569ZHlYQvOPwlrSIizk0MbJDGuOZ6mRlaCo/UXhu42AUCF4ALLFf48axd+IyM/W120RwkcZsjz5lnxERbHHQHahJ1o2bAf+/kYuotVsZLzXU70tJVVxe9e5fe0QkvudKdk3EKTLtsvREGm1GS49CBn3LCYki0FjjWQ9+k9ugMfmzcVt1+7Ywi9Efl2biHEt8q1buOMQwU7WJD5wLKG+hCoK98tdtspBfRKggsjFFWp3e9GQrS8hyLOP+eUs9IM/SCeEATlKhBGOZgPT8qz5X7O68="
  file:
    - "*.hst.gz"
    - "*.fxt.gz"
  file_glob: true
  skip_cleanup: true
  overwrite: true
  on:
    repo: FX-Data/FX-Data-EURGBP-DS
    tags: true
after_deploy:
- make clean
